### ISSUE TITLE
Can this synchronize the mouse operations of multiple windows?

### ISSUE THREAD

**Issue by rock0299999** [WowOpenBox/WowOpenBox#143]
Can this synchronize the mouse operations of multiple windows?

**Comment by mooreatv** [comment]
no, that would mean changing or sending mouse actions and that would be "input broadcasting software" which WOB can't do because we want to stay compliant.

this being said a funny side effect of windows10 is if you turn on both RR and mouse focus mode, Windows10 will move the mouse cursor to the middle of each window at each focus change.

hope that answers, if not do reopen
