### ISSUE TITLE
Questing regarding playing 6 accounts

### ISSUE THREAD

**Issue by maximus210793** [WowOpenBox/WowOpenBox#154]
Hi,
I am playing 6 accounts, and wanted to ask if it is possible that on my first monitor I have one account in fullscreen at 4k resolution and on my second monitor I have all remaining 5 windows in small?
I cannot find an option to play in fullscreen on my first monitor. Besides that 4K resolution is not recognized.
Thanks for your support.

**Comment by Rychard** [comment]
I play with 5 accounts, similar to what you're describing.

I have three monitors, the third is above the other two, but is excluded in WOB, leaving a blank area in the Window layout, but here's what that looks like:
![image](https://user-images.githubusercontent.com/2145848/215557287-25dbcb93-1bfc-4302-99d4-657a53a9d6ba.png)

As for the configuration, here's the relevant bits from the `.tcl` profile:

```tcl
	1,posXY	{0 0}
	1,size	{1920 1040}
	2,posXY	{-2880 0}
	2,size	{960 540}
	3,posXY	{-2880 540}
	3,size	{960 540}
	4,posXY	{-3840 0}
	4,size	{960 540}
	5,posXY	{-3840 540}
	5,size	{960 540}
```

You may notice that index `1` is sized at 1920x1040 (and all the other measurements seem to indicate a 1080p resolution), but this is merely due to the Windows DPI scaling being set to 200% on my monitors.  WoW itself is running in 4k.

**Comment by mooreatv** [comment]
Sorry I didn't see these open issues until now

I have 2 monitors and have full screen on main and 1/4 on the second one, you can do it if you uncheck "Same size for all" but depending on resolution you may have to exclude one of the monitor and put 4 windows first and then unexclude and add the main one
